apiVersion: v1
kind: Secret
metadata:
  name: backend-config 
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dummy: value
  {{- if or .Values.postgresql.configFile .Values.postgresqlExternal.configFile  }}
  INVENIO_DB_USER: {{ include "invenio.postgresql.username" . }}
  INVENIO_DB_HOST: {{ include "invenio.postgresql.hostname" . }}
  INVENIO_DB_PORT: {{ include "invenio.postgresql.portString" . }}
  INVENIO_DB_NAME: {{ include "invenio.postgresql.database" . }} 
  INVENIO_DB_PROTOCOL: "postgresql+psycopg2"
  {{- if or (and .Values.postgresql.enabled .Values.postgresql.auth.password) (and (not .Values.postgresql.enabled) .Values.postgresqlExternal.password) }}
  INVENIO_DB_PASSWORD: {{ include "invenio.postgresql.password" .  | quote }}
  {{- end }}
  {{- end }}

