{{- $namespace := .Release.Namespace -}}
{{- $ctx := .Values.opensearchExternal -}}
{{- $fields := list "username" "password" "hostname" "port" "useSsl" "protocol" "verifyCerts" "sslAssertHostname" "sslShowWarn" "caCerts" }}
{{- $data := dict }}
{{- $root := . }}

{{- range $field := $fields }}
  {{- $invenioHelper := (printf "%s%s" "invenio.opensearch." $field)  }}
  {{- $val := get $ctx $field }}
  {{- if $val }}
    {{- $_ := set $data $field (printf "%s" ($val | toString) | b64enc) }}
  {{- end }}
{{- end }}

{{- if gt (len $data) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ ((include "invenio.inline.secretName" (dict "myName" "opensearch" "root" $root)) | trim) }} 
  namespace: {{ $namespace }}
type: Opaque
data:
{{ toYaml $data | indent 2 }}
{{- end }}
