{{- $namespace := .Release.Namespace -}}
{{- $ctx := .Values.postgresqlExternal -}}
{{- $fields := fromJson (include "invenio.postgresql.fields" . | trim) }}
{{- $data := dict }}
{{- $root := . }}

{{- if $ctx.uri }}
  {{- $_ := set $data "uri" (printf "%s" ($ctx.uri | toString) | b64enc) }}
{{- else if not $ctx.uriKey }}
  {{- range $config, $envName := $fields }}
    {{- $invenioHelper := (printf "%s%s" "invenio.postgresql." $config)  }}
    {{- $val := fromYaml (include $invenioHelper $root | trim) }}
    {{- if or (eq $val.instance "internal") (eq $val.instance "external") }}
    {{- $_ := set $data $config (printf "%s" ($val.value | toString) | b64enc) }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if gt (len $data) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ ((include "invenio.inline.secretName" (dict "myName" "postgresql" "root" $root)) | trim) }} 
  namespace: {{ $namespace }}
type: Opaque
data:
{{- toYaml $data | nindent 2 }}
{{- end }}
