{{- $namespace := .Release.Namespace -}}
{{- $ctx := .Values.postgresqlExternal -}}
{{- $fields := list "uri" "username" "password" "hostname" "portString" "database" "protocol" }}
{{- $data := dict }}
{{- $root := . }}

{{- range $field := $fields }}
  {{- $val := get $ctx $field }}
  {{- if $val }}
    {{- $_ := set $data $field (printf "%s" ($val | toString) | b64enc) }}
  {{- end }}
{{- end }}

{{- if gt (len $data) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ ((include "invenio.inline.secretName" (dict "myName" "postgresql" "root" $root)) | trim) }} 
  namespace: {{ $namespace }}
type: Opaque
data:
{{- toYaml $data | nindent 2 }}
{{- end }}
