{{- $name := "invenio-redis-inline" -}}
{{- $namespace := .Release.Namespace -}}
{{- $ctx := .Values.redisExternal -}}
{{- $fields := list "password" "hostname" "port" "protocol" }}
{{- $data := dict }}

{{- range $field := $fields }}
  {{- $val := get $ctx $field }}
  {{- if $val }}
    {{- $_ := set $data $field (printf "%s" ($val | toString) | b64enc) }}
  {{- end }}
{{- end }}

{{- if gt (len $data) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
type: Opaque
data:
{{ toYaml $data | indent 2 }}
{{- end }}

