{{- $namespace := .Release.Namespace -}}
{{- $ctx := .Values.redisExternal -}}
{{- $fields := fromYaml (include "invenio.redis.fields" . | trim) }}
{{- $data := dict }}
{{- $root := . }}

{{- range $config, $envName := $fields }}
  {{- $invenioHelper := (printf "%s%s" "invenio.redis." $config)  }}
  {{- $val := fromYaml (include $invenioHelper $root | trim) }}
  {{- if or (eq $val.instance "internal") (eq $val.instance "external") }}
  {{- $_ := set $data $config (printf "%s" ($val.value | toString) | b64enc) }}
  {{- end }}
{{- end }}

{{- if gt (len $data) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ ((include "invenio.inline.secretName" (dict "myName" "redis" "root" $root)) | trim) }} 
  namespace: {{ $namespace }}
type: Opaque
data:
{{ toYaml $data | indent 2 }}
{{- end }}

