---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "invenio.fullname" . }}-worker
  labels:
    {{- include "invenio.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- with .Values.worker.deploymentSpec.minReadySeconds }}
  minReadySeconds: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.worker.deploymentSpec.paused }}
  paused: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.worker.deploymentSpec.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{- toYaml . | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.worker.replicas }}
  {{- with .Values.worker.deploymentSpec.revisionHistoryLimit }}
  revisionHistoryLimit: {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  {{- with .Values.worker.deploymentSpec.strategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- with .Values.worker.podAnnotations }}
          {{- tpl (toYaml .) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: worker
        checksum/invenio-config: {{ include (print $.Template.BasePath "/invenio-configmap.yaml") . | sha256sum }}
      labels:
        {{- with .Values.worker.podLabels }}
          {{- tpl (toYaml .) | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 -}}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 -}}
      {{- end }}
      containers:
      - name: worker
        image: {{ default .Values.worker.image (include "invenio.image" .) }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: [
            "/bin/bash",
            "-c",
            "celery -A {{ .Values.worker.app }} worker -c {{ .Values.worker.concurrency }} -l {{ .Values.worker.log_level }}"
        ]
        resources: {{- toYaml .Values.worker.resources | nindent 12 }}
        securityContext:
          {{- with .Values.worker.securityContext }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "invenio.fullname" . }}-config
        - secretRef:
            name: {{ include "invenio.secretName" . }}
        {{- with .Values.invenio.extraEnvFrom }}
        {{- tpl (. | toYaml) $ | nindent 8 }}
        {{- end }}
        {{- with .Values.worker.extraEnvFrom }}
        {{- tpl (. | toYaml) $ | nindent 8 }}
        {{- end }}
        env:
        - name: TZ
          value: {{ required "Missing .Values.global.timezone" .Values.global.timezone }}
        {{- if not .Values.rabbitmqExternal.configFile }}
        {{- include "invenio.config.queue" . | nindent 8 }}
        {{- end }}
        {{- if not .Values.postgresqlExternal.configFile }}
        {{- include "invenio.config.database" . | nindent 8 }}
        {{- end }}
        {{- if not .Values.redisExternal.configFile }}
        {{- include "invenio.config.cache" . | nindent 8 }}
        {{- end }}
        {{- if not .Values.opensearchExternal.configFile }}
        {{- (include "invenio.config.opensearch" . | trim) | nindent 8 }}
        {{- end }}
        {{- with .Values.invenio.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.worker.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "invenio.config.sentry" . | nindent 10 }}
        {{- include "invenio.config.datacite" . | nindent 10 }}
        {{- if .Values.invenio.remote_apps.enabled }}
        {{- range .Values.invenio.remote_apps.credentials }}
        - name: {{ default (printf "INVENIO_%s_APP_CREDENTIALS" .name) }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.invenio.remote_apps.secret_name }}
              key: {{ default (printf "INVENIO_%s_APP_CREDENTIALS" .name) }}
        {{- end }}
        {{- end }}
        {{- range .Values.invenio.extra_env_from_secret }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
        {{- end }}
        livenessProbe: {{- tpl (.Values.worker.livenessProbe | toYaml) $ | nindent 12 }}
        readinessProbe: {{- tpl (.Values.worker.readinessProbe | toYaml) $ | nindent 12 }}
        startupProbe: {{- tpl (.Values.worker.startupProbe | toYaml) $ | nindent 12 }}
        volumeMounts:
          - name: copy-configdata
            mountPath: /mounted/scripts
          - name: config-files
            mountPath: /configs
          {{- if .Values.persistence.enabled }}
          - mountPath: /opt/invenio/var/instance/data
            name: shared-volume
            subPath: data
          {{- end }}
          {{- if .Values.kerberos.enabled }}
          - name: kerberos-credentials-cache
            mountPath: /tmp
          {{- end }}
          {{- range $key, $value := .Values.invenio.vocabularies }}
          - name: vocabularies
            mountPath: "/opt/invenio/var/instance/app_data/vocabularies/{{ $key }}"
            subPath: "{{ $key }}"
          {{- end }}
      {{- if .Values.kerberos.enabled }}
      - name: kerberos-credentials
        image: {{ required "Missing .Values.kerberos.image" .Values.kerberos.image }}
        args: {{ .Values.kerberos.args }}
        envFrom:
          - secretRef:
              name: {{ .Values.kerberos.secret_name }}
        resources: {{- toYaml .Values.kerberos.resources | nindent 12 }}
        {{- if .Values.kerberos.readinessProbe }}
        readinessProbe: {{- toYaml .Values.kerberos.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.kerberos.livenessProbe }}
        livenessProbe: {{- toYaml .Values.kerberos.livenessProbe | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: kerberos-credentials-cache
            mountPath: /tmp
      {{- end }}

      initContainers:
        # copy configfiles
        - name: copy-configfiles
          image: {{ default .Values.web.image (include "invenio.image" .) }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: [
              "/bin/bash",
              "/mounted/scripts/copy.sh"
          ]
          resources: {{- toYaml .Values.web.initContainers.resources | nindent 12 }}
          securityContext:
            {{- with .Values.worker.securityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
          - name: copy-configdata
            mountPath: /mounted/scripts
          - name: config-files
            mountPath: /configs
          {{- if .Values.postgresqlExternal.configFile }}
          - name: postgresql-config
            mountPath: /mounted/postgresql
          {{- end }}
          {{- if .Values.rabbitmqExternal.configFile }}
          - name: rabbitmq-config
            mountPath: /mounted/rabbitmq
          {{- end }}
          {{- if .Values.redisExternal.configFile }}
          - name: redis-config
            mountPath: /mounted/redis
          {{- end }}
          {{- if .Values.opensearchExternal.configFile }}
          - name: opensearch-config
            mountPath: /mounted/opensearch
          {{- end }}
          {{- if .Values.invenio.extraConfigFiles }}
          - name: extra-configfiles
            mountPath: /mounted/extra
          {{- end }}

      {{- if .Values.kerberos.enabled }}
        # Init kerberos credentials
        - name: init-kerberos-credentials
          image: {{ required "Missing .Values.kerberos.image" .Values.kerberos.image }}
          args: {{ .Values.kerberos.initArgs }}
          envFrom:
            - secretRef:
                name: {{ .Values.kerberos.secret_name }}
          resources: {{- toYaml .Values.kerberos.initContainers.resources | nindent 12 }}
          volumeMounts:
            - name: kerberos-credentials-cache
              mountPath: /tmp
      {{- end }}
      securityContext:
        {{- with .Values.worker.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config-files
          emptyDir: {}
        - name: copy-configdata
          projected:
            sources:
              - secret:
                  name: {{ include "invenio.fullname" . }}-copy-configfiles
                  items:
                  - key: copy.sh
                    path: copy.sh
        {{- if .Values.invenio.extraConfigFiles }}
        {{- include "invenio.extraConfigFiles" . | nindent 8 }}
        {{- end }}
        {{- if .Values.postgresqlExternal.configFile }}
        {{- include "invenio.postgresql.configFile" . | nindent 8 }}
        {{- end }}
        {{- if .Values.rabbitmqExternal.configFile }}
        {{- include "invenio.rabbitmq.configFile" . | nindent 8 }}
        {{- end }}
        {{- if .Values.redisExternal.configFile }}
        {{- include "invenio.redis.configFile" . | nindent 8 }}
        {{- end }}
        {{- if .Values.opensearchExternal.configFile }}
        {{- include "invenio.opensearch.configFile" . | nindent 8 }}
        {{- end }}

        {{- if .Values.persistence.enabled }}
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}
        {{- end }}
        {{- if .Values.kerberos.enabled }}
        - name: kerberos-credentials-cache
          emptyDir: {}
        {{- end }}
        {{- if .Values.invenio.vocabularies }}
        - name: vocabularies
          configMap:
            name: "{{ include "invenio.fullname" . }}-vocabularies"
        {{- end }}
      {{- if .Values.worker.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.worker.imagePullSecret }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
